# Generated by Django 5.1.7 on 2025-03-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TTSJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("created_data", models.DateTimeField(auto_now_add=True)),
                ("file_location", models.CharField(max_length=255)),
                ("download_link", models.CharField(blank=True, max_length=255)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
