# Generated by Django 5.1.7 on 2025-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TTS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ttsjob",
            name="file_location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
