# Generated by Django 5.1.7 on 2025-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TTS", "0002_alter_ttsjob_file_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ttsjob",
            name="download_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ttsjob",
            name="file_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ttsjob",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
    ]
