# Generated by Django 5.1.7 on 2025-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TTS", "0003_alter_ttsjob_download_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ttsjob",
            name="download_link",
            field=models.CharField(blank=True, default="N/A", max_length=255),
        ),
        migrations.AlterField(
            model_name="ttsjob",
            name="file_location",
            field=models.CharField(blank=True, default="N/A", max_length=255),
        ),
    ]
