# Generated by Django 5.1.7 on 2025-03-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TTS", "0004_alter_ttsjob_download_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ttsjob",
            old_name="created_data",
            new_name="created_date",
        ),
    ]
