# Generated by Django 5.1.7 on 2025-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTS', '0005_rename_created_data_ttsjob_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsjob',
            name='audio_file',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
    ]
