# Generated by Django 5.1.7 on 2025-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STTJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_location', models.CharField(default='N/A', max_length=150)),
                ('download_link', models.CharField(default='N/A', max_length=150)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('text_file', models.CharField(default='N/A', max_length=150)),
            ],
        ),
    ]
